//This is a result program generated by AI agent. This is not a part of original codebase.
const readline = require('readline');
const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
let userInput = [];
rl.question('How many inputs do you want to provide? ', (num) => {
  let count = parseInt(num);
  let i = 0;
  function readInput() {
    rl.question(`Enter input #${i + 1}: `, (input) => {
      userInput.push(input);
      i++;
      if (i < count) {
        readInput();
      } else {
        console.log('Your inputs:');
        console.log(userInput);
        rl.close();
      }
    });
  }
  readInput();
});
